language: node_js
node_js:
  - "0.10"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem install sass
before_script:
  - npm install grunt-cli -g
  - npm install
script:
  - grunt
